name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  test_and_build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Run unit tests
        run: npm run test
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  tag_release:
    needs: [test_and_build]
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' }}  # Only deploy on push (not PRs)
    steps:
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    needs: test_and_build  # Wait for tests to pass first!
    concurrency: deploy-group
    if: ${{ github.event_name == 'push' }}  # Only deploy on push (not PRs)
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}